### ISSUE TITLE
Userstory 1

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#1]
---
name: User Story
about: A default user story
title: "Navbar"
labels: ''
assignees: ''

---

## Value statement - a requirement, not a solution
As a user
I need navbar
so that i can navigate to the pages

## Acceptance criteria
- [ ] the App should have a Header
- [ ] the App should have a Navbar and a three pages
- [ ] Navbar and Header should be styled

## Tasks
- [ ]  add the Header
- [ ] add the Navbar
- [ ] create links to each Page
- [ ] style the created components

## Size
(small, medium, large)
