### ISSUE TITLE
Userstory 7: total sum and "buy" button

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#10]
## Value statement - a requirement, not a solution
As a  user 
I need to see the total sum of my products and a button to buy all products
so that i can use it

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/198005625-cf4a133d-05e8-4091-a6d6-d9b018e8b836.png)

## Acceptance criteria
- [ ] the shopping cart has an area where i can see the sum 
- [ ] the shopping cart has a button where i can click(for the first time this button has no function, but further)
- [ ] the total sum function works correctly

## Tasks
- [ ] create some div  teg down to the page that contains the total sum
- [ ] create functions that counts the sum
- [ ] create the button called "buy" (further becomes it a function)

## Size
(small, medium, large)
