### ISSUE TITLE
Input for personal data

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#13]
## Value statement - a requirement, not a solution
As a  user
I need to have an opportunity to input my personal data
so that i can see it when I order new shoes

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/199200567-6f61ed03-9feb-4b75-9c36-661b264f5d71.png)

## Acceptance criteria
- [ ] input has fields for name, email, address.
- [ ] input field is shown in a new page
- [ ] input values should be saved
- [ ] after submit all data is rendered on the page 

## Tasks
- [ ] create a new Page
- [ ] create an input field in it
- [ ] take and save all data from input field
- [ ] render all the input data after submitting

## Size
(small, medium, large)
