### ISSUE TITLE
create History page

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#15]
## Value statement - a requirement, not a solution
As a  user 
I need to have an access to my order history
so that i can every time see what i ordered 

## Acceptance criteria
- [ ] history page is created
- [ ] after i submitt Bestelldetails all ordered items moves to history page
- [ ] after i submitt Bestelldetails all ordered items should be removed from shopping card

## Tasks
- [ ] create a history page
- [ ] move all ordered items in history page
- [ ] delete all ordered items from shopping card
