### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#18]
## Value statement - a requirement, not a solution
As a  user
I need to have an ability to leave a feedback after buying the shoes
so that the feedback can be shown in a details page later

## Acceptance criteria
- [ ] history page has a  button which navigates you to the feedback form
- [ ] feedback form has two fields (user and feedback)
- [ ] after i submit the feedback it can be seen in details page
- [ ] details page has a button which toggles the feedback to be visible or not 

## Tasks
- [ ] create a feedback button in History page
- [ ] create an input fields for feedback
- [ ] create state for feedback input
- [ ] show your feedback in a details page with a toggle function
