### ISSUE TITLE
Userstory 3

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#2]
## Value statement - a requirement, not a solution
As a  user 
I need to see filtered products when enter the search
so that  i can look through the products

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/197609302-4e5adbe0-866b-4c1b-8caf-db2a70d0be29.png)

## Acceptance criteria
- [ ] the first page become a list of filtered items after entering the values of the item
- [ ] the items should be rendered between Navbar(down) and search field
- [ ] the products should display an image, title and price

## Tasks
- [ ] create a file with an array
- [ ] use fetch function and to get the array from the file
- [ ] use fast fuzzy search in order to display only necessary products
- [ ] create a list that renderes each product down to the search field
- [ ] make a style for all items
- [ ] look if the filter works correctly

## Size
(small, medium, large)
