### ISSUE TITLE
Bookmark page

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#20]
## Value statement - a requirement, not a solution
As a  user i want to have an ability to save my items to favourites
so that i can take a look later what i saved there

## Acceptance criteria
- [ ] new Bookmark page is created 
- [ ] Bookmark page is styled in the same way as a homePage
- [ ] each Item becomes a bookmark button

## Tasks
- [ ] create a new Page called Favourites
- [ ] style this Page
- [ ] add a new bookmarkButton to each Item
- [ ] create a functions for this
