### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#23]
## Value statement - a requirement, not a solution
As a  developer
I need to be sure that created components/parts works
so that i can use it

## Acceptance criteria
- [ ]  tests are written
- [ ] tests works

## Tasks
- [ ] write a few tests 
- [ ]  run this tests and check wether they works correctly
