### ISSUE TITLE
UserStory 2

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#3]
## Value statement - a requirement, not a solution
As a user
I need to see the search field
so that i can write something there

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/197607779-9b6f2917-8a8b-47ba-95dd-dc5aa9869419.png)

## Acceptance criteria
- [ ] only the first page has a search loop
- [ ] the search loop is write under the Header component
- [ ] the input can be seen in console log for the first time

## Tasks
- [ ] create a search field directly under the Header comp
- [ ] style it
- [ ] make the input of the search field to be seen in the console for the first time

## Size
(small, medium, large)

**Comment by s-kond** [comment]
You forgot to estimate a size (small, medium. large)! And what do you mean by "search loop"? 🤔

**Comment by nazardiachok** [comment]
hmm, what do you mean Stefan with size? search loop is das Eingabefeld. Perhaps it was not the right word to describe

**Comment by s-kond** [comment]
we should estimate the time for every userstory - will it be a small, medium or large user story (-> see the last part of your userstory).
ah okay, I would say it's a 'search field' or 'search input' 🤷‍♂️
