### ISSUE TITLE
User Story 4: Details

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#7]
## Value statement - a requirement, not a solution
As a  user 
I need to have a button
so that i can see the details of the products

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/197992094-04cff22c-332a-48b4-b7b0-d707b745258a.png),

![image](https://user-images.githubusercontent.com/111637550/197992246-e8cb0e80-a0ce-418b-8f63-0d9bad66c9e2.png)

## Acceptance criteria
- [ ]  each element of the array should have a details button
- [ ] when clicked button should open the details of the currently product 

## Tasks
- [ ] create a button in SectionOutput
- [ ] create a function to  run the details on display
- [ ] display window should have a button to close  details

## Size
(small, medium, large)
