### ISSUE TITLE
Userstory 5: shopping cart 

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#8]
## Value statement - a requirement, not a solution
As a  user
I need have a shopping cart
so that i can put my products into this cart

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/197995881-497a51a5-6702-4c6d-ac38-571926fb1976.png)

## Acceptance criteria
- [ ] each product item should also have a button to put a product in a shopping cart 
- [ ] shopping carts are rendered on its own page

## Tasks
- [ ] create a new button in each element at homePage with the title"add to carts"
- [ ] create a new list of items at a shopping cart page after adding to the shopping cart 
- [ ] style added elements

## Size
(small, medium, large)
