### ISSUE TITLE
User Story 6: delete and input field

### ISSUE THREAD

**Issue by nazardiachok** [nazardiachok/Capstone-New-Project#9]
## Value statement - a requirement, not a solution
As a  user
I need to see button on each of  added items and input filed
so that i can change the number of added products and i can delete each of them

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/111637550/198004524-1d032ebb-9414-413b-b6bf-741edb1ae655.png)

## Acceptance criteria
- [ ] there is a delete button on each added item
- [ ] there is an input field on each added item
- [ ] there are 2 functions 
- [ ] when click on the button or change input - function works

## Tasks
- [ ] create a delete button, style it
- [ ] create an input field, style it
- [ ] create functions that can delete item and change the number

## Size
(small, medium, large)
